name: Check

permissions:
  contents: read

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install hack
        uses: taiki-e/install-action@cargo-hack

      - name: Format
        run: cargo fmt --all -- --check

      - name: Check main
        run: cargo hack --feature-powerset --keep-going check --verbose --workspace

      - name: Check examples
        run: cargo hack --feature-powerset --keep-going check --verbose --workspace --examples

      - name: Check tests
        run: cargo hack --feature-powerset --keep-going check --verbose --workspace --tests

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Clippy main
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --all-features

      - name: Clippy tests
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --all-features --tests

      - name: Clippy examples
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose --workspace --examples

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: dtolnay/rust-toolchain@stable

      - name: Install hack
        uses: taiki-e/install-action@cargo-hack

      - name: Test
        run: cargo hack --feature-powerset --keep-going test --verbose --workspace --no-fail-fast -- --nocapture

  docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cargo doc
        run: cargo doc --no-deps --all-features
